# Generated by Django 4.1.7 on 2023-03-15 14:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Properity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='property/feature_image/', verbose_name='Feature Image')),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('no_of_bedroom', models.IntegerField(blank=True, null=True, verbose_name='Number of Bedroom')),
                ('no_of_bathroom', models.IntegerField(blank=True, null=True, verbose_name='Number of Bathroom')),
                ('li_title1', ckeditor.fields.RichTextField()),
                ('no_of_kitchen', models.IntegerField(blank=True, null=True, verbose_name='Number of Kitchen')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='property/author_image/', verbose_name='Author Image')),
                ('author_name', models.CharField(blank=True, max_length=233, null=True, verbose_name='Author Name')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_engine.category')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_engine.propertytype')),
            ],
        ),
    ]
