# Generated by Django 4.1.7 on 2023-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='individual',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(choices=[(False, 'Individual'), (True, 'Agent')], default=1),
            preserve_default=False,
        ),
    ]
